name: Python Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t gmail-reader-app .

    # Nếu có test thì mở dòng dưới ra, không có thì bỏ qua
    # - name: Run tests
    #   run: pytest

    # Kiểm tra chạy thử Flask app (tuỳ chọn, nếu muốn check chạy OK)
    # - name: Run Flask app check (optional)
    #   run: |
    #     python app.py &
    #     sleep 10
    #     curl -f http://localhost:5000 || exit 1
    #   continue-on-error: true
